spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_security
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect